$engine: 3
$onesync: on
name: RipGrep server data scanner

tasks: 
  - action: download_file
    url: https://github.com/tabarra/temp-test-recipe/releases/latest/download/ripgrep-recipe.zip
    path: ./ripgrep-recipe.zip

  - action: unzip
    src: ./ripgrep-recipe.zip
    dest: ./
